server:
  port: 8002
spring:
  application:
    name: qiding-jiaguo-gateway
  cloud:
    gateway:
      routes:
        - id: qiding-jiaguo-user
          uri: lb://qiding-jiaguo-user/
          predicates:
            - Path=/user/**
  zipkin:
    sender:
      type: web
    base-url: http://qiding-jiaguo-zipkin/
    service:
      name: ${spring.application.name}
eureka:
  client:
    service-url:
      defaultZone: http://eureka.qiding.com:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
logging:
  pattern:
    console: "[@project.artifactId@] %clr([%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%p] => %C.%M\\(%F:%L\\) - %m%n"